// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // But you can create a sidebar manually
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  tutorialSidebar: [
    {
      type: "category",
      label: "📖 Game Story",
      link: { type: "doc", id: "Game-Story/index" },
      items: [
        "Game-Story/Discovery-of-MoveTopia",
        {
          type: "category",
          label: "The Story of the Land",
          link: { type: "doc", id: "Game-Story/The-Story-of-the-Land/index" },
          items: [
            "Game-Story/The-Story-of-the-Land/Aurora-Terra",
            "Game-Story/The-Story-of-the-Land/Novaris-City",
            "Game-Story/The-Story-of-the-Land/Valkyrium-Nexus",
            "Game-Story/The-Story-of-the-Land/Omnium-Core",
          ],
        },
        "Game-Story/Journey-of-the-Players",
      ],
    },
    {
      type: "category",
      label: "🚀 Introduction",
      link: { type: "doc", id: "Introduction/index" },
      items: ["Introduction/Vision"],
    },
    {
      type: "category",
      label: "🎭 Game Roles and Resources",
      link: {
        type: "doc",
        id: "Game-Roles-and-Resources/index",
      },
      items: [
        "Game-Roles-and-Resources/Landers",
        {
          type: "category",
          label: "Sources",
          link: {
            type: "doc",
            id: "Game-Roles-and-Resources/Sources/index",
          },
          items: [
            "Game-Roles-and-Resources/Sources/Aurum",
            "Game-Roles-and-Resources/Sources/Glister",
            "Game-Roles-and-Resources/Sources/Ascension-Pulse",
          ],
        },
      ],
    },

    {
      type: "category",
      label: "⚙️ Game Mechanics",
      link: { type: "doc", id: "Game-Mechanics/index" },
      items: [
        {
          type: "category",
          label: "Game Loop",
          link: { type: "doc", id: "Game-Mechanics/Game-Loop/index" },
          items: [
            "Game-Mechanics/Game-Loop/Placement-of-NFT-Items-in-the-Field",
            "Game-Mechanics/Game-Loop/Resource-Claiming-in-Certain-Periods",
          ],
        },
        {
          type: "category",
          label: "Use and Transformation of Resources",
          link: {
            type: "doc",
            id: "Game-Mechanics/Use-and-Transformation-of-Resources/index",
          },
          items: [
            "Game-Mechanics/Use-and-Transformation-of-Resources/Aurum-$TOPIA-Stake",
            "Game-Mechanics/Use-and-Transformation-of-Resources/Glister-Usage",
          ],
        },
        "Game-Mechanics/Use-of-Booster-NFTs",
      ],
    },
    {
      type: "category",
      label: "💰 Game Economics",
      link: { type: "doc", id: "Game-Economics/index" },
      items: [
        "Game-Economics/Reward-Mechanism",
        {
          type: "category",
          label: "MoveTopia Token",
          link: { type: "doc", id: "Game-Economics/MoveTopia-Token/index" },
          items: [
            "Game-Economics/MoveTopia-Token/MoveTopia-Tokenomics",
            "Game-Economics/MoveTopia-Token/Vesting-Schedule",
          ],
        },
        {
          type: "category",
          label: "On-Chain Assets",
          link: { type: "doc", id: "Game-Economics/On-Chain-Assets/index" },
          items: [
            "Game-Economics/On-Chain-Assets/NFTs",
            "Game-Economics/On-Chain-Assets/Tradable-and-Non-Tradable-Commodities",
          ],
        },
        "Game-Economics/Off-Chain-Assets",
      ],
    },
    {
      type: "category",
      label: "🏛️ DAO",
      link: { type: "doc", id: "DAO/index" },
      items: ["DAO/Ascension-Pulse", "DAO/Voting-Processes"],
    },

    { type: "doc", id: "Official-Links/index", label: "🔗 Official Links" },
  ],
};

export default sidebars;
